[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

# The repository root is resolved relative to this script (scripts\..), so the working directory does not matter.
$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$CheckpointsDir = Join-Path $Root "checkpoints"
$ArchiveDir = Join-Path $CheckpointsDir "archive"
$CurrentFile = Join-Path $CheckpointsDir "Current-Checkpoint.md"
$NewFile = Join-Path $CheckpointsDir "New-Checkpoint.md"

function Stop-WithError {
    param([string]$Message)
    Write-Host ""
    Write-Error $Message
    exit 1
}

try {
    Write-Host "Chief of Staff checkpoint rotation"
    Write-Host "Repository: $Root"
    Write-Host ""

    # Validate expected repository structure and files.
    if (-not (Test-Path -LiteralPath $CheckpointsDir -PathType Container)) {
        Stop-WithError "Could not find the 'checkpoints' folder. Expected layout: <repo>\scripts\Rotate-Checkpoint.ps1 and <repo>\checkpoints\."
    }

    if (-not (Test-Path -LiteralPath $NewFile -PathType Leaf)) {
        Stop-WithError "Missing checkpoints\New-Checkpoint.md. Save the checkpoint generated by the agent with that exact filename, then run this script again."
    }

    if (-not (Test-Path -LiteralPath $CurrentFile -PathType Leaf)) {
        Stop-WithError "Missing checkpoints\Current-Checkpoint.md. Rotation stopped so no existing checkpoint is lost."
    }

    # Basic validation that the new file looks like a complete checkpoint.
    $NewContent = Get-Content -LiteralPath $NewFile -Raw
    if ([string]::IsNullOrWhiteSpace($NewContent)) {
        Stop-WithError "New-Checkpoint.md is empty. Rotation stopped."
    }

    $FirstNonBlankLine = ($NewContent -split "`r?`n" |
        Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
        Select-Object -First 1).Trim([char]0xFEFF).TrimEnd()

    if ($FirstNonBlankLine -ne "# Chief of Staff Checkpoint") {
        Stop-WithError "New-Checkpoint.md does not begin with '# Chief of Staff Checkpoint'. Rotation stopped."
    }

    if ($NewContent -notmatch '(?m)^##\s+Checkpoint Metadata\s*$') {
        Stop-WithError "New-Checkpoint.md is missing the '## Checkpoint Metadata' section. It may be incomplete. Rotation stopped."
    }

    if ($NewContent -notmatch '(?im)^\s*-?\s*Status:\s*Current\s*$') {
        Stop-WithError "New-Checkpoint.md metadata does not include 'Status: Current'. It may be incomplete. Rotation stopped."
    }

    # Create archive directory if needed.
    if (-not (Test-Path -LiteralPath $ArchiveDir -PathType Container)) {
        New-Item -ItemType Directory -Path $ArchiveDir | Out-Null
    }

    # Name the archive by the moment of archiving (to the second), not by any date
    # the agent wrote into the checkpoint. Agent-written dates may be date-only,
    # missing, or unparseable, which previously caused same-day filename collisions.
    # If a file with that name still exists, add a numeric suffix. Never overwrite.
    $Stamp = (Get-Date).ToString("yyyy-MM-dd-HHmmss")
    $ArchiveFile = Join-Path $ArchiveDir ("Checkpoint-{0}.md" -f $Stamp)
    $Suffix = 1
    while (Test-Path -LiteralPath $ArchiveFile) {
        $ArchiveFile = Join-Path $ArchiveDir ("Checkpoint-{0}-{1:00}.md" -f $Stamp, $Suffix)
        $Suffix++
    }

    # Archive current checkpoint.
    Copy-Item -LiteralPath $CurrentFile -Destination $ArchiveFile

    if (-not (Test-Path -LiteralPath $ArchiveFile -PathType Leaf)) {
        Stop-WithError "Archive verification failed. Current checkpoint was not replaced."
    }

    # Extra verification: archived bytes must match current bytes before promotion.
    $CurrentHash = (Get-FileHash -LiteralPath $CurrentFile -Algorithm SHA256).Hash
    $ArchiveHash = (Get-FileHash -LiteralPath $ArchiveFile -Algorithm SHA256).Hash

    if ($CurrentHash -ne $ArchiveHash) {
        Stop-WithError "Archive integrity verification failed. Current checkpoint was not replaced."
    }

    # Promote the new checkpoint in a single replacing move so there is never a
    # moment with no Current-Checkpoint.md. The verified archive already exists.
    Move-Item -LiteralPath $NewFile -Destination $CurrentFile -Force

    if (-not (Test-Path -LiteralPath $CurrentFile -PathType Leaf)) {
        Stop-WithError "Promotion verification failed. The archived checkpoint is safe at: $ArchiveFile"
    }

    if (Test-Path -LiteralPath $NewFile) {
        Stop-WithError "New-Checkpoint.md still exists after promotion. Review the checkpoints folder."
    }

    Write-Host "Rotation complete."
    Write-Host ""
    Write-Host "Archived previous checkpoint:"
    Write-Host "  $ArchiveFile"
    Write-Host ""
    Write-Host "Promoted new checkpoint:"
    Write-Host "  $CurrentFile"
    Write-Host ""
    Write-Host "You can now allow OneDrive to sync, start a new Chief of Staff conversation, and run Status."
}
catch {
    Write-Host ""
    Write-Error "Checkpoint rotation failed: $($_.Exception.Message)"
    exit 1
}
