[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

# Run this script from the Chief-of-Staff repository root.
$Root = (Get-Location).Path
$CheckpointsDir = Join-Path $Root "checkpoints"
$ArchiveDir = Join-Path $CheckpointsDir "archive"
$CurrentFile = Join-Path $CheckpointsDir "Current-Checkpoint.md"
$NewFile = Join-Path $CheckpointsDir "New-Checkpoint.md"

function Stop-WithError {
    param([string]$Message)
    Write-Host ""
    Write-Error $Message
    exit 1
}

try {
    Write-Host "Chief of Staff checkpoint rotation"
    Write-Host "Repository: $Root"
    Write-Host ""

    # Validate expected repository structure and files.
    if (-not (Test-Path -LiteralPath $CheckpointsDir -PathType Container)) {
        Stop-WithError "Could not find the 'checkpoints' folder. Run this script from the Chief-of-Staff repository root."
    }

    if (-not (Test-Path -LiteralPath $NewFile -PathType Leaf)) {
        Stop-WithError "Missing checkpoints\New-Checkpoint.md. Save the checkpoint generated by the agent with that exact filename, then run this script again."
    }

    if (-not (Test-Path -LiteralPath $CurrentFile -PathType Leaf)) {
        Stop-WithError "Missing checkpoints\Current-Checkpoint.md. Rotation stopped so no existing checkpoint is lost."
    }

    # Basic validation that the new file looks like a checkpoint.
    $FirstNonBlankLine = Get-Content -LiteralPath $NewFile |
        Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
        Select-Object -First 1

    if ($FirstNonBlankLine -ne "# Chief of Staff Checkpoint") {
        Stop-WithError "New-Checkpoint.md does not begin with '# Chief of Staff Checkpoint'. Rotation stopped."
    }

    # Create archive directory if needed.
    if (-not (Test-Path -LiteralPath $ArchiveDir -PathType Container)) {
        New-Item -ItemType Directory -Path $ArchiveDir | Out-Null
    }

    # Prefer the checkpoint-generated date from the existing Current file.
    # Fall back to the file's LastWriteTime if metadata cannot be parsed.
    $CurrentContent = Get-Content -LiteralPath $CurrentFile -Raw
    $Timestamp = $null

    $Patterns = @(
        '(?im)^\s*-\s*Checkpoint generated:\s*(.+?)\s*$',
        '(?im)^\s*Checkpoint generated:\s*(.+?)\s*$'
    )

    foreach ($Pattern in $Patterns) {
        $Match = [regex]::Match($CurrentContent, $Pattern)
        if ($Match.Success) {
            $RawDate = $Match.Groups[1].Value.Trim()
            $ParsedDate = [datetime]::MinValue

            if ([datetime]::TryParse($RawDate, [ref]$ParsedDate)) {
                $Timestamp = $ParsedDate
                break
            }
        }
    }

    if ($null -eq $Timestamp) {
        $Timestamp = (Get-Item -LiteralPath $CurrentFile).LastWriteTime
    }

    $BaseArchiveName = "Checkpoint-{0}.md" -f $Timestamp.ToString("yyyy-MM-dd-HHmm")
    $ArchiveFile = Join-Path $ArchiveDir $BaseArchiveName

    # Never silently overwrite an archive.
    if (Test-Path -LiteralPath $ArchiveFile) {
        Stop-WithError "Archive already exists: $ArchiveFile`nNo files were changed. Resolve the filename collision before retrying."
    }

    # Archive current checkpoint.
    Copy-Item -LiteralPath $CurrentFile -Destination $ArchiveFile

    if (-not (Test-Path -LiteralPath $ArchiveFile -PathType Leaf)) {
        Stop-WithError "Archive verification failed. Current checkpoint was not replaced."
    }

    # Extra verification: archived bytes must match current bytes before promotion.
    $CurrentHash = (Get-FileHash -LiteralPath $CurrentFile -Algorithm SHA256).Hash
    $ArchiveHash = (Get-FileHash -LiteralPath $ArchiveFile -Algorithm SHA256).Hash

    if ($CurrentHash -ne $ArchiveHash) {
        Stop-WithError "Archive integrity verification failed. Current checkpoint was not replaced."
    }

    # Promote the new checkpoint. Move-Item replaces neither silently nor partially:
    # remove current only after a verified archive exists, then move new into place.
    Remove-Item -LiteralPath $CurrentFile
    Move-Item -LiteralPath $NewFile -Destination $CurrentFile

    if (-not (Test-Path -LiteralPath $CurrentFile -PathType Leaf)) {
        Stop-WithError "Promotion verification failed. The archived checkpoint is safe at: $ArchiveFile"
    }

    if (Test-Path -LiteralPath $NewFile) {
        Stop-WithError "New-Checkpoint.md still exists after promotion. Review the checkpoints folder."
    }

    Write-Host "Rotation complete."
    Write-Host ""
    Write-Host "Archived previous checkpoint:"
    Write-Host "  $ArchiveFile"
    Write-Host ""
    Write-Host "Promoted new checkpoint:"
    Write-Host "  $CurrentFile"
    Write-Host ""
    Write-Host "You can now allow OneDrive to sync, start a new Chief of Staff conversation, and run Status."
}
catch {
    Write-Host ""
    Write-Error "Checkpoint rotation failed: $($_.Exception.Message)"
    exit 1
}
